# ============================================================================ 
# PRE-COMMIT CONFIGURATION FOR BU-PROCESSOR 
# ============================================================================ 
repos:
  # BLACK - Python code formatter
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: ["--line-length=88"]
        language_version: python3

  # ISORT - Import statement organizer
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile=black", "--multi-line=3"]
        language_version: python3

  # FLAKE8 - Python linter für Style-Checks
  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - "--max-line-length=88"
          - "--extend-ignore=E203,W503,E501"
          - "--max-complexity=10"
        language_version: python3

  # TRAILING-WHITESPACE & File checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements

  # MYPY - Static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        args: ["--ignore-missing-imports", "--no-strict-optional"]
        language_version: python3

  # BANDIT - Security linter for Python
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        language_version: python3
