# ============================================================================ 
# PRE-COMMIT CONFIGURATION FOR BU-PROCESSOR 
# ============================================================================ 
repos:
  # BLACK - Python code formatter
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: ["--line-length=88"]
        language_version: python3

  # ISORT - Import statement organizer
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile=black", "--multi-line=3"]
        language_version: python3

  # FLAKE8 - Python linter für Style-Checks
  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - "--max-line-length=88"
          - "--extend-ignore=E203,W503,E501"
          - "--max-complexity=10"
        language_version: python3

  # TRAILING-WHITESPACE & File checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements

  # MYPY - Static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        args: ["--ignore-missing-imports", "--no-strict-optional"]
        language_version: python3

  # BANDIT - Security linter for Python
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        language_version: python3

  # ========================================================================
  # CUSTOM REPO HYGIENE CHECKS
  # ========================================================================
  - repo: local
    hooks:
      - id: no-tests-in-package
        name: 🧪 Ensure tests stay outside package directory
        entry: bash -c 'if git diff --cached --name-only | grep -E "^bu_processor/bu_processor/.+test_.+\.py$"; then echo "❌ Tests must not live in package dir (bu_processor/bu_processor/). Place them in tests/ or bu_processor/tests/"; exit 1; fi'
        language: system
        always_run: true
        pass_filenames: false
        
      - id: no-test-imports-in-package
        name: 🧪 Ensure no test imports in production code
        entry: bash -c 'if git diff --cached --name-only | grep -E "^bu_processor/bu_processor/.+\.py$" | xargs grep -l "import.*test" 2>/dev/null; then echo "❌ Production code should not import test modules"; exit 1; fi'
        language: system
        always_run: true
        pass_filenames: false
        
      - id: check-test-file-placement
        name: 🧪 Verify test files are in correct directories
        entry: bash -c 'if git diff --cached --name-only | grep -E "test_.+\.py$" | grep -v -E "^(tests/|bu_processor/tests/)"; then echo "⚠️ Test files should be in tests/ or bu_processor/tests/ directories"; fi'
        language: system
        always_run: true
        pass_filenames: false
