blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/yourusername/bu-processor/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 📚 Documentation
    url: https://github.com/yourusername/bu-processor/wiki
    about: Check our comprehensive documentation and guides
  - name: 🔧 API Documentation
    url: http://localhost:8000/docs
    about: Interactive API documentation (start local server first)
